[workspace]
members = [
    "crates/application",
    "crates/kernel",
    "crates/platform",
    "crates/primitives",
]
exclude = ["xtask"]
default-members = ["crates/application"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
