[build]
target = "aarch64-unknown-none"

[alias]
image = "run --quiet --manifest-path xtask/Cargo.toml --target aarch64-apple-darwin"
qemu = "run --release"

[target.aarch64-unknown-none]
runner = "scripts/qemu.sh"
rustflags = [
    "-C", "link-arg=-Tcrates/kernel/linker.ld",
    "-C", "link-arg=--gc-sections",
]
