[package]
name = "trains-application"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
trains-kernel = { path = "../kernel" }
trains-platform = { path = "../platform" }
trains-primitives = { path = "../primitives" }

[[bin]]
name = "trains-kernel"
path = "src/main.rs"
test = false
bench = false
